config/routes.rb
Rails.application.routes.draw do
  resources :signups
  root 'signups#new'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/signup.rb
class Signup < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/signups_controller.rb
class SignupsController < ApplicationController
  before_action :set_signup, only: [:show, :edit, :update, :destroy]

  # GET /signups
  # GET /signups.json
  def index
    @signups = Signup.all
  end

  # GET /signups/1
  # GET /signups/1.json
  def show
  end

  # GET /signups/new
  def new
    @signup = Signup.new
  end

  # GET /signups/1/edit
  def edit
  end

  # POST /signups
  # POST /signups.json
  def create
    @signup = Signup.new(signup_params)

    if verify_recaptcha(model: @signup) && @signup.save
      redirect_to @signup
    else
      render 'new'
    end

  end

  # PATCH/PUT /signups/1
  # PATCH/PUT /signups/1.json
  def update
    respond_to do |format|
      if @signup.update(signup_params)
        format.html { redirect_to @signup, notice: 'Signup was successfully updated.' }
        format.json { render :show, status: :ok, location: @signup }
      else
        format.html { render :edit }
        format.json { render json: @signup.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /signups/1
  # DELETE /signups/1.json
  def destroy
    @signup.destroy
    respond_to do |format|
      format.html { redirect_to signups_url, notice: 'Signup was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_signup
      @signup = Signup.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def signup_params
      params.require(:signup).permit(:name, :password, :email, :comments)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/signups_helper.rb
module SignupsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>SampleApplreCapcha</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/signups/_form.html.erb
<%= form_with(model: signup, local: true) do |form| %>
  <% if signup.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(signup.errors.count, "error") %> prohibited this signup from being saved:</h2>

      <ul>
      <% signup.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.text_field :password %>
  </div>

  <div class="field">
    <%= form.label :email %>
    <%= form.text_field :email %>
  </div>

  <div class="field">
    <%= form.label :comments %>
    <%= form.text_area :comments %>
  </div>

  <%= recaptcha_tags %>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/signups/edit.html.erb
<h1>Editing Signup</h1>

<%= render 'form', signup: @signup %>

<%= link_to 'Show', @signup %> |
<%= link_to 'Back', signups_path %>

app/views/signups/index.html.erb
<head>
<script src='https://www.google.com/recaptcha/api.js'></script>
</head>
<p id="notice"><%= notice %></p>

<h1>Signups</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Password</th>
      <th>Email</th>
      <th>Comments</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @signups.each do |signup| %>
      <tr>
        <td><%= signup.name %></td>
        <td><%= signup.password %></td>
        <td><%= signup.email %></td>
        <td><%= signup.comments %></td>
        <td><%= link_to 'Show', signup %></td>
        <td><%= link_to 'Edit', edit_signup_path(signup) %></td>
        <td><%= link_to 'Destroy', signup, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Signup', new_signup_path %>

app/views/signups/new.html.erb
<h1>New Signup</h1>

<%= render 'form', signup: @signup %>

<%= link_to 'Back', signups_path %>

app/views/signups/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @signup.name %>
</p>

<p>
  <strong>Password:</strong>
  <%= @signup.password %>
</p>

<p>
  <strong>Email:</strong>
  <%= @signup.email %>
</p>

<p>
  <strong>Comments:</strong>
  <%= @signup.comments %>
</p>

<%= link_to 'Edit', edit_signup_path(@signup) %> |
<%= link_to 'Back', signups_path %>